"""
Splits the critical edges of the CFG: edges from a block with several successors to a block with several
predecessors get an empty edge block with an unconditional jump. The layout generation then can assume that
the predecessors of a join have a single successor (see Definition 3.3 in the paper), so the output stack
of a conditional jump is never unified with the other predecessors of one of its successors.

In the Yul CFGs generated by solc, the latches of the loops jump unconditionally to the header, so no back
edge is critical: the critical edges are the fall-through of a conditional jump into a join (an if without
else). The layout generation looks through edge blocks to keep the stack of the conditional block along the
then-branch (see LayoutGeneration._dominant_through_edge_block), and the edge blocks that end up doing nothing
are not emitted (see solution_generation.reconstruct_bytecode)
"""
import logging
from parser.cfg import CFG
from parser.cfg_block_list import CFGBlockList
from cfg_methods.cfg_block_actions.edge_block import insert_edge_block


def split_critical_edges_cfg(cfg: CFG) -> int:
    """
    Splits the critical edges of every block list in the CFG (objects, functions and subobjects).
    Returns the number of edge blocks inserted
    """
    num_edge_blocks = 0
    for cfg_object in cfg.objectCFG.values():
        num_edge_blocks += split_critical_edges_block_list(cfg_object.blocks)
        for cfg_function in cfg_object.functions.values():
            num_edge_blocks += split_critical_edges_block_list(cfg_function.blocks)

        sub_object = cfg_object.get_subobject()
        if sub_object is not None:
            num_edge_blocks += split_critical_edges_cfg(sub_object)
    return num_edge_blocks


def split_critical_edges_block_list(block_list: CFGBlockList) -> int:
    """
    Splits the critical edges of the block list, traversing the blocks in order and their successors in
    (jumps to, falls to) order. Returns the number of edge blocks inserted
    """
    critical_edges = []
    for block_id, block in block_list.blocks.items():
        if len(block.successors) <= 1:
            continue
        for successor_id in block.successors:
            if len(block_list.get_block(successor_id).get_comes_from()) > 1:
                critical_edges.append((block_id, successor_id))

    for pred_block_id, successor_id in critical_edges:
        insert_edge_block(block_list, pred_block_id, successor_id).splits_critical_edge = True

    if critical_edges:
        # Invalidate the cached graph structures
        block_list.graph = None
        block_list._dominant_tree = None
        block_list._loop_nesting_forest = None
        logging.info(f"Split {len(critical_edges)} critical edges in {block_list.name}")
    return len(critical_edges)
