"""
Simplifications that solc's legacy optimizer (CSE, peephole...) performs on the code generated by solc but not
on grey's code, as they depend on how the values are placed in the stack. They are applied directly on the CFG
(see scripts/cse.md)
"""
from parser.cfg import CFG
from parser.cfg_block_list import CFGBlockList


def is_literal(arg: str) -> bool:
    return arg.startswith("0x")


def return_to_stop_block_list(block_list: CFGBlockList) -> int:
    """
    Replaces return(offset, 0) by stop() when the offset is a literal. Both finish the execution successfully with
    no return data, but STOP is a single instruction and needs no arguments. solc's CSE only does it when the zero
    size is pushed in the same CSE block as the RETURN, whereas grey may push it earlier (e.g. before a LOG)
    """
    replaced = 0
    for block in block_list.blocks.values():
        for instruction in block.get_instructions():
            if instruction.get_op_name() != "return":
                continue
            offset, size = instruction.get_in_args()
            if is_literal(size) and int(size, 16) == 0 and is_literal(offset):
                instruction.set_op_name("stop")
                instruction.set_in_args([])
                replaced += 1
    return replaced


def apply_cse_rules_cfg(cfg: CFG) -> int:
    replaced = 0
    for cfg_object in cfg.objectCFG.values():
        replaced += return_to_stop_block_list(cfg_object.blocks)
        for cfg_function in cfg_object.functions.values():
            replaced += return_to_stop_block_list(cfg_function.blocks)

        sub_object = cfg_object.get_subobject()

        if sub_object is not None:
            replaced += apply_cse_rules_cfg(sub_object)
    return replaced
