"""
Merges equivalent blocks in the acyclic tails of the CFG (the blocks from which no loop can be reached).
Two blocks are equivalent if (1) they contain the same instructions, (2) the variables they use have
a one-to-one correspondence and (3) their successors are also equivalent. solc deduplicates such
blocks in the legacy optimizer only if they have the same stack layout, which rarely happens with the
layouts generated by grey. Hence, we merge them beforehand, introducing phi-functions for the values
that correspond to each other but are not the same variable.

The blocks are traversed bottom-up, so equivalent successors have already been merged when a block
is visited, and condition (3) amounts to having exactly the same successors.
"""
import logging
from typing import Dict, List, Optional, Set, Tuple, Any
import networkx as nx
from global_params.types import block_id_T, var_id_T
from parser.cfg import CFG
from parser.cfg_block import CFGBlock
from parser.cfg_block_list import CFGBlockList
import parser.opcodes as opcodes
from cfg_methods.cfg_block_actions.merge_equivalent_blocks import MergeEquivalentBlocks
from cfg_methods.cfg_block_actions.utils import modify_comes_from, modify_successors
from cfg_methods.utils import union_find_search


class FreshVariables:
    """
    Generates variable names that do not appear in the CFG
    """

    def __init__(self, used_variables: Set[var_id_T]):
        self._used_variables = used_variables
        self._next_idx = 0

    def __call__(self, base_var: var_id_T) -> var_id_T:
        new_var = f"{base_var}_eq{self._next_idx}"
        while new_var in self._used_variables:
            self._next_idx += 1
            new_var = f"{base_var}_eq{self._next_idx}"
        self._next_idx += 1
        self._used_variables.add(new_var)
        return new_var


def merge_equivalent_blocks_cfg(cfg: CFG) -> int:
    """
    Merges the equivalent blocks in the acyclic tails of every block list in the CFG.
    Returns the number of removed blocks
    """
    fresh_variables = FreshVariables(_variables_cfg(cfg))
    return _merge_equivalent_blocks_cfg(cfg, fresh_variables)


def _merge_equivalent_blocks_cfg(cfg: CFG, fresh_variables: FreshVariables) -> int:
    removed_blocks = 0
    for object_id, cfg_object in cfg.objectCFG.items():
        removed_blocks += merge_equivalent_blocks_block_list(cfg_object.blocks, fresh_variables)

        for function_name, cfg_function in cfg_object.functions.items():
            removed_blocks += merge_equivalent_blocks_block_list(cfg_function.blocks, fresh_variables)

        sub_object = cfg_object.get_subobject()

        if sub_object is not None:
            removed_blocks += _merge_equivalent_blocks_cfg(sub_object, fresh_variables)
    return removed_blocks


def _variables_cfg(cfg: CFG) -> Set[var_id_T]:
    """
    All the variables that appear in the CFG (including the subobjects), to generate fresh ones
    """
    variables = set()
    for cfg_object in cfg.objectCFG.values():
        block_lists = [cfg_object.blocks] + [cfg_function.blocks for cfg_function in cfg_object.functions.values()]
        for cfg_function in cfg_object.functions.values():
            variables.update(cfg_function.arguments)
        for block_list in block_lists:
            for block in block_list.blocks.values():
                for instr in block.get_instructions():
                    variables.update(instr.get_in_args())
                    variables.update(instr.get_out_args())
                if block.get_condition() is not None:
                    variables.add(block.get_condition())

        sub_object = cfg_object.get_subobject()
        if sub_object is not None:
            variables.update(_variables_cfg(sub_object))
    return variables


def merge_equivalent_blocks_block_list(block_list: CFGBlockList, fresh_variables: FreshVariables) -> int:
    """
    Merges the equivalent blocks in the acyclic tails of the block list, traversing the blocks bottom-up.
    Returns the number of removed blocks
    """
    # The graph is cached and might be outdated
    block_list.graph = None
    candidates = _acyclic_tail_blocks(block_list)
    assigned_variables = {assigned_value for assigned_value in block_list.assigment_dict.values()
                          if not assigned_value.startswith("0x")}

    # Signature -> representative block id (dict to keep the order deterministic)
    representatives: Dict[Tuple[Any, ...], block_id_T] = dict()
    # Representatives that have absorbed some block and successors that have lost a predecessor
    # (dicts as ordered sets)
    merged_representatives: Dict[block_id_T, None] = dict()
    reduced_successors: Dict[block_id_T, None] = dict()
    removed_blocks = 0

    for block_id in _bottom_up_order(block_list, candidates):
        block = block_list.get_block(block_id)
        signature_info = canonical_signature(block, block_list)
        if signature_info is None:
            continue
        signature, block_inputs = signature_info

        representative_id = representatives.get(signature, None)
        if representative_id is None:
            representatives[signature] = block_id
            continue

        representative = block_list.get_block(representative_id)
        representative_signature, representative_inputs = canonical_signature(representative, block_list)
        assert representative_signature == signature, \
            f"Merging must preserve the signature of the representative {representative_id}"

        if not _can_merge(representative, representative_inputs, block, assigned_variables):
            continue

        if not _is_profitable(representative, representative_inputs, block, block_inputs, block_list):
            continue

        reduced_successors.update(dict.fromkeys(block.successors))
        MergeEquivalentBlocks(representative, representative_inputs, block, block_inputs,
                              block_list, fresh_variables).perform_action()
        merged_representatives[representative_id] = None
        removed_blocks += 1

    if removed_blocks > 0:
        _remove_single_entry_phis(block_list, list(reduced_successors.keys()))
        _split_edges(block_list, list(merged_representatives.keys()))

        # Invalidate the cached graph structures
        block_list.graph = None
        block_list._dominant_tree = None
        block_list._loop_nesting_forest = None
        logging.info(f"Merged {removed_blocks} equivalent blocks in {block_list.name}")

    return removed_blocks


def _can_merge(representative: CFGBlock, representative_inputs: List[var_id_T], duplicate: CFGBlock,
               assigned_variables: Set[var_id_T]) -> bool:
    """
    Conditions not captured by the signature. The blocks cannot share predecessors, as the predecessor
    would reach the merged block twice (possibly with different values for the phi-functions).
    The input variables of the representative that might be renamed cannot appear in the assignment dict
    of the block list, as it would become incoherent
    """
    if set(representative.get_comes_from()).intersection(duplicate.get_comes_from()):
        return False
    return all(input_var not in assigned_variables for input_var in representative_inputs)


# Estimated number of bytes of the edge blocks introduced for splitting critical edges (JUMPDEST, PUSH tag, JUMP)
EDGE_BLOCK_SIZE = 5


def _estimated_size(block: CFGBlock) -> int:
    """
    Rough estimation of the number of bytes of the block: one byte per instruction plus the PUSHes of the
    constants. Stack-managing instructions are ignored, as they are not known at this point
    """
    size = 0
    for instr in block.instructions_without_phi_functions():
        # Function calls involve pushing two tags and a jump
        size += 1 if instr.get_op_name().upper() in opcodes.opcodes else 7
        for in_arg in instr.get_in_args():
            if in_arg.startswith("0x"):
                constant_value = int(in_arg, 16)
                size += 1 if constant_value == 0 else 1 + (constant_value.bit_length() + 7) // 8
    return size


def _is_profitable(representative: CFGBlock, representative_inputs: List[var_id_T], duplicate: CFGBlock,
                   duplicate_inputs: List[var_id_T], block_list: CFGBlockList) -> bool:
    """
    Estimates whether removing the duplicate saves bytes. The overhead comes from the edge blocks
    (see _split_edges) needed for the predecessors with several successors and all but one of the
    predecessors that fall to the merged block, and the stack movements for the values that become
    phi-functions (roughly one SWAP/DUP per incoming edge)
    """
    merged_ids = {representative.block_id, duplicate.block_id}
    predecessors = representative.get_comes_from() + duplicate.get_comes_from()

    num_conditional_predecessors = sum(len(block_list.get_block(pred_block_id).successors) > 1
                                       for pred_block_id in predecessors)
    num_falling_predecessors = sum(len(block_list.get_block(pred_block_id).successors) == 1 and
                                   block_list.get_block(pred_block_id).get_falls_to() in merged_ids
                                   for pred_block_id in predecessors)
    num_edge_blocks = num_conditional_predecessors + max(0, num_falling_predecessors - 1)

    num_phi_values = sum(representative_var != duplicate_var
                         for representative_var, duplicate_var in zip(representative_inputs, duplicate_inputs))

    overhead = EDGE_BLOCK_SIZE * num_edge_blocks + num_phi_values * len(predecessors)
    return _estimated_size(duplicate) > overhead


def _remove_single_entry_phis(block_list: CFGBlockList, reduced_block_ids: List[block_id_T]) -> None:
    """
    A block whose predecessors have been merged into a single one keeps phi-functions with a single
    argument, which the layout generation does not handle (phi-functions are only considered when unifying
    the stacks of several predecessors). These phi-functions are removed and their output renamed to the
    argument everywhere in the block list: as the block has a single predecessor, the argument dominates
    every use of the phi output
    """
    renaming_dict: Dict[var_id_T, var_id_T] = dict()
    for block_id in reduced_block_ids:
        block = block_list.get_block(block_id)
        if len(block.get_comes_from()) != 1 or len(block.phi_instructions()) == 0:
            continue

        for phi_instr in block.phi_instructions():
            assert len(phi_instr.get_in_args()) == 1, f"Phi-function {phi_instr} in {block_id} must have a single argument"
            renaming_dict[phi_instr.get_out_args()[0]] = phi_instr.get_in_args()[0]

        block.get_instructions()[:] = block.instructions_without_phi_functions()
        block.entries = []

    if len(renaming_dict) == 0:
        return

    # Phi arguments might be phi outputs removed as well
    def renamed(variable: var_id_T) -> var_id_T:
        return union_find_search(variable, renaming_dict)

    for block in block_list.blocks.values():
        for instr in block.get_instructions():
            instr.set_in_args([renamed(in_arg) for in_arg in instr.get_in_args()])
        if block.get_condition() is not None:
            block.set_condition(renamed(block.get_condition()))

    # Updated in place, as the blocks share the same dict
    for out_var, in_var in block_list.assigment_dict.items():
        block_list.assigment_dict[out_var] = renamed(in_var)


def _split_edges(block_list: CFGBlockList, merged_block_ids: List[block_id_T]) -> None:
    """
    Inserts empty blocks with an unconditional jump in the edges that break two assumptions of the later
    phases, which merging can violate. It is done once all the blocks have been merged, so that the
    predecessors can be merged as well in the bottom-up traversal:
    1. The predecessors of a block with several predecessors have a single successor (no critical edges).
       The layout generation unifies their output stacks and removes the junk of all but one of them,
       which would remove the values needed by the other successor of a conditional jump.
    2. A block is the "falls to" of at most one predecessor, as the reconstruction places a falls-to
       block right after its predecessor.
    """
    for merged_block_id in merged_block_ids:
        merged_block = block_list.get_block(merged_block_id)
        if len(merged_block.get_comes_from()) <= 1:
            continue

        for pred_block_id in list(merged_block.get_comes_from()):
            if len(block_list.get_block(pred_block_id).successors) > 1:
                _insert_edge_block(block_list, pred_block_id, merged_block_id)

        # Edge blocks reach the merged block with a jump, so only other blocks can fall to it
        falling_predecessors = [pred_block_id for pred_block_id in merged_block.get_comes_from()
                                if block_list.get_block(pred_block_id).get_falls_to() == merged_block_id]
        # The first one keeps falling to the merged block
        for pred_block_id in falling_predecessors[1:]:
            _insert_edge_block(block_list, pred_block_id, merged_block_id)


def _insert_edge_block(block_list: CFGBlockList, pred_block_id: block_id_T, successor_id: block_id_T) -> None:
    """
    Inserts an empty block with an unconditional jump in the edge from pred_block_id to successor_id
    """
    edge_block_id = f"{pred_block_id}_to_{successor_id}"
    assert edge_block_id not in block_list.blocks, f"Block {edge_block_id} already exists"
    pred_block = block_list.get_block(pred_block_id)
    edge_block = CFGBlock(edge_block_id, [], "unconditional", pred_block.assignment_dict)
    edge_block.set_comes_from([pred_block_id])
    edge_block.set_jump_to(successor_id)
    block_list.add_block(edge_block)

    modify_successors(pred_block_id, successor_id, edge_block_id, block_list)
    modify_comes_from(successor_id, pred_block_id, edge_block_id, block_list)


def _acyclic_tail_blocks(block_list: CFGBlockList) -> Set[block_id_T]:
    """
    Blocks (other than the start block) from which no cycle can be reached
    """
    graph = block_list.to_graph()
    blocks_in_cycles = set()
    for component in nx.strongly_connected_components(graph):
        if len(component) > 1:
            blocks_in_cycles.update(component)
        else:
            node = next(iter(component))
            if graph.has_edge(node, node):
                blocks_in_cycles.add(node)

    reaching_cycles = set(blocks_in_cycles)
    for node in blocks_in_cycles:
        reaching_cycles.update(nx.ancestors(graph, node))

    return {block_id for block_id in block_list.blocks
            if block_id not in reaching_cycles and block_id != block_list.start_block}


def _bottom_up_order(block_list: CFGBlockList, candidates: Set[block_id_T]) -> List[block_id_T]:
    """
    Candidates sorted by height (longest path to a terminal block) and then by post-order. When a block of
    height h is visited, all the blocks of smaller height have been visited, so no more blocks will be merged
    into its successors and their phi-functions (part of the signature) do not change afterwards. Merges
    among blocks of height h only modify blocks of height h (the representatives), their predecessors
    (greater height) and the phi arguments of the successors along the edges from the removed blocks
    """
    post_order = [block_id for block_id in _post_order(block_list) if block_id in candidates]
    height: Dict[block_id_T, int] = dict()
    for block_id in post_order:
        # The successors of candidates are also candidates and appear before in the post-order
        height[block_id] = max((height[successor] + 1 for successor in block_list.get_block(block_id).successors),
                               default=0)
    position = {block_id: i for i, block_id in enumerate(post_order)}
    return sorted(post_order, key=lambda block_id: (height[block_id], position[block_id]))


def _post_order(block_list: CFGBlockList) -> List[block_id_T]:
    """
    Post-order traversal of the blocks (successors before predecessors in the acyclic parts),
    starting from the start block and following the deterministic order of the successors
    """
    visited = set()
    order = []
    roots = [block_list.start_block] + [block_id for block_id in block_list.blocks
                                        if block_id != block_list.start_block]
    for root in roots:
        if root is None or root in visited:
            continue
        visited.add(root)
        stack = [(root, iter(block_list.get_block(root).successors))]
        while stack:
            node, successors_iterator = stack[-1]
            next_successor = next(successors_iterator, None)
            if next_successor is None:
                stack.pop()
                order.append(node)
            elif next_successor not in visited:
                visited.add(next_successor)
                stack.append((next_successor, iter(block_list.get_block(next_successor).successors)))
    return order


def canonical_signature(block: CFGBlock, block_list: CFGBlockList) \
        -> Optional[Tuple[Tuple[Any, ...], List[var_id_T]]]:
    """
    Canonical representation of the block, abstracting away the variable names: constants are kept,
    variables defined in the block are numbered by definition order and the remaining ones (the inputs,
    including the phi outputs) by order of first use. The uses at the end of the block (the condition
    and the phi arguments of the successors along the edges from the block) are also considered.
    Two blocks with the same signature are equivalent, and their inputs correspond position-wise.
    Returns None if the block cannot be merged
    """
    jump_to, falls_to = block.get_jump_to(), block.get_falls_to()
    if jump_to is not None and jump_to == falls_to:
        return None

    phi_instrs = block.phi_instructions()
    if len(phi_instrs) > 0 and sorted(block.entries) != sorted(block.get_comes_from()):
        return None

    local_vars: Dict[var_id_T, int] = dict()
    input_vars: Dict[var_id_T, int] = dict()

    def canonical_use(variable: var_id_T) -> Tuple[str, Any]:
        if variable.startswith("0x"):
            return "c", variable
        if variable in local_vars:
            return "l", local_vars[variable]
        return "i", input_vars.setdefault(variable, len(input_vars))

    canonical_instrs = []
    for instr in block.instructions_without_phi_functions():
        canonical_ins = tuple(canonical_use(in_arg) for in_arg in instr.get_in_args())
        for out_arg in instr.get_out_args():
            local_vars[out_arg] = len(local_vars)
        literal_args = tuple(instr.get_literal_args()) if instr.get_literal_args() is not None else ()
        canonical_instrs.append((instr.get_op_name(), literal_args, instr.get_builtin_op(),
                                 canonical_ins, len(instr.get_out_args())))

    end_uses = []
    if block.get_condition() is not None:
        end_uses.append(canonical_use(block.get_condition()))

    for successor_id in block.successors:
        successor = block_list.get_block(successor_id)
        successor_phis = successor.phi_instructions()
        if len(successor_phis) > 0:
            if block.block_id not in successor.entries:
                return None
            entry_idx = successor.entries.index(block.block_id)
            end_uses.append(tuple(canonical_use(phi_instr.get_in_args()[entry_idx])
                                  for phi_instr in successor_phis))
        else:
            end_uses.append(())

    # Dead phi-functions are not handled
    if any(phi_instr.get_out_args()[0] not in input_vars for phi_instr in phi_instrs):
        return None

    signature = (block.get_jump_type(), jump_to, falls_to, tuple(canonical_instrs), tuple(end_uses))
    return signature, list(input_vars.keys())
