from parser.cfg_block import CFGBlock
from parser.cfg_block_list import CFGBlockList
from parser.cfg_instruction import CFGInstruction
from cfg_methods.return_labels import hoist_return_labels_block_list, shared_blocks


def build_block_list(blocks, edges):
    """
    The first block is the start one. Edges are (source, target, "jumps_to" | "falls_to")
    """
    block_list = CFGBlockList("object")
    for block in blocks:
        block_list.add_block(block)
    for u, v, kind in edges:
        block_list.blocks[v].add_comes_from(u)
        if kind == "jumps_to":
            block_list.blocks[u].set_jump_to(v)
        else:
            block_list.blocks[u].set_falls_to(v)
    return block_list


def call_block(block_id: str, label: str) -> CFGBlock:
    """
    Sub-block that calls function f with return label "label" (as generated by split_blocks_cfg)
    """
    call = CFGInstruction("f", [], [])
    call.in_args = ["1", "v0", label]
    block = CFGBlock(block_id, [CFGInstruction("PUSH [tag]", [], ["1"]), CFGInstruction("PUSH [tag]", [], [label]),
                                call], "sub_block", dict())
    block.split_instruction = call
    return block


def conditional_block(block_id: str) -> CFGBlock:
    jumpi = CFGInstruction("JUMPI", [], [])
    block = CFGBlock(block_id, [CFGInstruction("calldataload", ["0x00"], ["v0"]), jumpi], "conditional", dict())
    block.split_instruction = jumpi
    return block


def plain_block(block_id: str) -> CFGBlock:
    jump = CFGInstruction("JUMP", [], [])
    block = CFGBlock(block_id, [jump], "unconditional", dict())
    block.split_instruction = jump
    return block


def terminal_block(block_id: str) -> CFGBlock:
    revert = CFGInstruction("revert", ["0x00", "0x00"], [])
    block = CFGBlock(block_id, [revert], "terminal", dict())
    block.split_instruction = revert
    return block


def pushes(block_list, label):
    return [block_id for block_id, block in block_list.blocks.items()
            for instr in block.get_instructions()
            if instr.get_op_name() == "PUSH [tag]" and instr.get_out_args() == [label]]


class TestReturnLabels:

    def test_hoisted_to_the_branch_point(self):
        # b -> (b1, b2) -> join (call with label 7) -> cont: the label is pushed in b
        blocks = [conditional_block("b"), plain_block("b1"), plain_block("b2"), call_block("join", "7"),
                  terminal_block("cont")]
        block_list = build_block_list(blocks, [("b", "b1", "jumps_to"), ("b", "b2", "falls_to"),
                                               ("b1", "join", "jumps_to"), ("b2", "join", "jumps_to"),
                                               ("join", "cont", "falls_to")])
        assert hoist_return_labels_block_list(block_list, {"f"}, "branch") == 1
        assert pushes(block_list, "7") == ["b"]
        # The push is placed before the split instruction of b and the call keeps the label as last argument
        assert block_list.get_block("b").get_instructions()[-2].get_out_args() == ["7"]
        assert block_list.get_block("join").split_instruction.get_in_args()[-1] == "7"

    def test_not_hoisted_above_a_path_that_does_not_call(self):
        # b -> (r, c) where r reverts: the call in c does not post-dominate b
        blocks = [conditional_block("b"), terminal_block("r"), call_block("c", "7"), terminal_block("cont")]
        block_list = build_block_list(blocks, [("b", "r", "jumps_to"), ("b", "c", "falls_to"),
                                               ("c", "cont", "falls_to")])
        assert hoist_return_labels_block_list(block_list, {"f"}, "max") == 0
        assert pushes(block_list, "7") == ["c"]

    def test_branch_strategy_stops_at_the_nearest_branch_point(self):
        # a -> b -> (b1, b2) -> join (call): "branch" hoists to b, "max" up to a; a straight line is not hoisted
        def build():
            blocks = [plain_block("a"), conditional_block("b"), plain_block("b1"), plain_block("b2"),
                      call_block("join", "7"), terminal_block("cont")]
            return build_block_list(blocks, [("a", "b", "jumps_to"), ("b", "b1", "jumps_to"), ("b", "b2", "falls_to"),
                                             ("b1", "join", "jumps_to"), ("b2", "join", "jumps_to"),
                                             ("join", "cont", "falls_to")])
        block_list = build()
        hoist_return_labels_block_list(block_list, {"f"}, "branch")
        assert pushes(block_list, "7") == ["b"]
        block_list = build()
        hoist_return_labels_block_list(block_list, {"f"}, "max")
        assert pushes(block_list, "7") == ["a"]

        straight = build_block_list([plain_block("a"), call_block("c", "7"), terminal_block("cont")],
                                    [("a", "c", "jumps_to"), ("c", "cont", "falls_to")])
        assert hoist_return_labels_block_list(straight, {"f"}, "branch") == 0

    def test_not_hoisted_out_of_a_loop(self):
        # entry -> header -> (body, exit), body = call with label 7, body -> latch -> header
        blocks = [plain_block("entry"), conditional_block("header"), call_block("body", "7"), plain_block("latch"),
                  terminal_block("exit")]
        block_list = build_block_list(blocks, [("entry", "header", "jumps_to"), ("header", "body", "jumps_to"),
                                               ("header", "exit", "falls_to"), ("body", "latch", "falls_to"),
                                               ("latch", "header", "jumps_to")])
        hoist_return_labels_block_list(block_list, {"f"}, "max")
        # The call does not post-dominate the header (the loop can exit), and the entry is outside the loop
        assert pushes(block_list, "7") == ["body"]

    def test_shared_strategy_pushes_at_the_lowest_non_shared_block(self):
        # Two copies of site_i -> shared_i -> call_i, where the sites compute different things: the labels are
        # pushed in the sites (the shared blocks and the calls are identical in both copies)
        def site(block_id, constant):
            jump = CFGInstruction("JUMP", [], [])
            block = CFGBlock(block_id, [CFGInstruction("calldataload", [constant], ["v0"]), jump], "unconditional",
                             dict())
            block.split_instruction = jump
            return block
        blocks = [site("site1", "0x00"), plain_block("shared1"), call_block("call1", "7"), terminal_block("cont1")]
        first = build_block_list(blocks, [("site1", "shared1", "jumps_to"), ("shared1", "call1", "jumps_to"),
                                          ("call1", "cont1", "falls_to")])
        blocks = [site("site2", "0x20"), plain_block("shared2"), call_block("call2", "8"),
                  CFGBlock("cont2", [CFGInstruction("stop", [], [])], "terminal", dict())]
        second = build_block_list(blocks, [("site2", "shared2", "jumps_to"), ("shared2", "call2", "jumps_to"),
                                           ("call2", "cont2", "falls_to")])
        second.name = "other"
        shared = shared_blocks([first, second], {"f"})
        # The continuations differ (revert vs stop), but they do not count for the calls
        assert ("object", "call1") in shared and ("other", "call2") in shared
        assert ("object", "shared1") in shared and ("object", "site1") not in shared
        assert hoist_return_labels_block_list(first, {"f"}, "shared", shared) == 1
        assert pushes(first, "7") == ["site1"]

    def test_unique_call_is_not_hoisted(self):
        blocks = [conditional_block("b"), plain_block("b1"), plain_block("b2"), call_block("join", "7"),
                  terminal_block("cont")]
        block_list = build_block_list(blocks, [("b", "b1", "jumps_to"), ("b", "b2", "falls_to"),
                                               ("b1", "join", "jumps_to"), ("b2", "join", "jumps_to"),
                                               ("join", "cont", "falls_to")])
        shared = shared_blocks([block_list], {"f"})
        assert ("object", "join") not in shared
        assert hoist_return_labels_block_list(block_list, {"f"}, "shared", shared) == 0

    def test_shared_strategy_respects_the_stack_pressure(self, monkeypatch):
        # Same two copies as above: v0 is live across shared1 and call1, so with a small reachable depth the label
        # of call1 cannot be carried from site1 (nor from shared1)
        import global_params.constants as constants

        def build():
            def site(block_id, constant):
                jump = CFGInstruction("JUMP", [], [])
                block = CFGBlock(block_id, [CFGInstruction("calldataload", [constant], ["v0"]), jump],
                                 "unconditional", dict())
                block.split_instruction = jump
                return block
            first = build_block_list([site("site1", "0x00"), plain_block("shared1"), call_block("call1", "7"),
                                      terminal_block("cont1")],
                                     [("site1", "shared1", "jumps_to"), ("shared1", "call1", "jumps_to"),
                                      ("call1", "cont1", "falls_to")])
            second = build_block_list([site("site2", "0x20"), plain_block("shared2"), call_block("call2", "8"),
                                       terminal_block("cont2")],
                                      [("site2", "shared2", "jumps_to"), ("shared2", "call2", "jumps_to"),
                                       ("call2", "cont2", "falls_to")])
            second.name = "other"
            return first, shared_blocks([first, second], {"f"})

        monkeypatch.setattr(constants, "MAX_STACK_DEPTH", 3)
        first, shared = build()
        assert hoist_return_labels_block_list(first, {"f"}, "shared", shared) == 0
        assert pushes(first, "7") == ["call1"]

        monkeypatch.setattr(constants, "MAX_STACK_DEPTH", 4)
        first, shared = build()
        assert hoist_return_labels_block_list(first, {"f"}, "shared", shared) == 1
        assert pushes(first, "7") == ["site1"]

    def test_inline_candidates(self):
        # g: a single block returning (inlined by solc); h: a chain that only calls g (inlined once g is);
        # k: branches, so it is never inlined; m: calls k
        from cfg_methods.return_labels import inline_candidates

        def function_return(block_id):
            return CFGBlock(block_id, [CFGInstruction("calldataload", ["0x00"], ["v0"])], "FunctionReturn", dict())

        def calling(block_id, callee):
            call = CFGInstruction(callee, [], [])
            block = CFGBlock(block_id, [call], "sub_block", dict())
            block.split_instruction = call
            return block

        g = build_block_list([function_return("g0")], [])
        h = build_block_list([calling("h0", "g"), function_return("h1")], [("h0", "h1", "falls_to")])
        k = build_block_list([conditional_block("k0"), function_return("k1"), function_return("k2")],
                             [("k0", "k1", "jumps_to"), ("k0", "k2", "falls_to")])
        m = build_block_list([calling("m0", "k"), function_return("m1")], [("m0", "m1", "falls_to")])
        assert inline_candidates({"g": g, "h": h, "k": k, "m": m}) == {"g", "h"}
