import collections
import copy
import argparse
import json
import re
from typing import Dict, Optional, List
from pathlib import Path
from timeit import default_timer as dtimer
from collections import defaultdict

import pandas as pd

from parser.utils_parser import split_json
from global_params.types import Yul_CFG_T
from parser.parser import parse_CFG_from_json_dict
from parser.cfg import CFG
from execution.sol_compilation import SolidityCompilation, importer_deduplicates_blocks
from solution_generation.reconstruct_bytecode import asm_from_cfg, store_asm_output, store_binary_output, \
    store_asm_standard_json_output, restrict_importer_inlining
from greedy.ids_from_spec import cfg_spec_ids, cfg_push_to_dup, cfg_block_list_spec_ids, cfg_object_spec_ids
from liveness.layout_generation import layout_generation, layout_generation_cfg
from liveness.liveness_analysis import construct_analysis_info, perform_liveness_analysis_from_cfg_info
from liveness.calling_convention import candidate_functions, undo_calling_conventions
from cfg_methods.preprocessing_methods import preprocess_cfg
from solution_generation.bytecode2asm import asm_from_opcodes
from reparation.repair_unreachable import repair_cfg
from analysis.solution_analysis import function_frequency
import global_params.constants as constants
from global_params.debug import debug_file
from solution_generation.store_sfs import sfs_from_cfg

global times
times = []


def yul_cfg_dict_from_format(input_format: str, filename: str, contract: Optional[str],
                             solc_executable: str = "solc") -> Dict[str, Yul_CFG_T]:
    """
    Returns a dict of the Yul CFG JSONS that are generated from the compilation of a contract
    """
    if input_format == "yul-cfg":
        # We assume there can be multiple JSONS inside a single file
        return split_json(filename), {}
    elif input_format == "sol":
        return SolidityCompilation.from_single_solidity_code(filename, contract, solc_executable=solc_executable), {}
    elif input_format == "standard-json":
        # First load the input file
        with open(filename, 'r') as f:
            input_contract = json.load(f)
            settings_opt = input_contract["settings"]
        return SolidityCompilation.from_json_input(input_contract, contract, original_folder=str(Path(filename).parent),
                                                   solc_executable=solc_executable), settings_opt
    else:
        raise ValueError(f"Input format {input_format} not recognized.")


def _candidate_costs(cfg: CFG, candidates: Dict[str, set], components: Dict[str, set]) -> Dict:
    """
    Cost of each candidate function with the code generated by the greedy (only the affected components have it): its
    own blocks, the blocks that call it (they prepare the arguments) and the blocks that follow the calls (they receive
    the returned values). Keys: (object name, function name)
    """
    costs = dict()
    for object_name, functions in candidates.items():
        cfg_object = cfg.objectCFG[object_name]
        for function_name in functions:
            costs[(object_name, function_name)] = sum(len(block.greedy_ids) for block in
                                                      cfg_object.functions[function_name].blocks.blocks.values())
        for component_name in components[object_name]:
            block_list = _block_list_of(cfg_object, object_name, component_name)
            for block in block_list.blocks.values():
                split_instruction = block.split_instruction
                if split_instruction is None or split_instruction.get_op_name() not in functions:
                    continue
                key = (object_name, split_instruction.get_op_name())
                costs[key] += len(block.greedy_ids)
                falls_to = block.get_falls_to()
                if falls_to is not None and falls_to in block_list.blocks:
                    costs[key] += len(block_list.blocks[falls_to].greedy_ids)
    return costs


def _components_calling(cfg_object, object_name: str, functions: set) -> set:
    """
    The given functions and the components (main code, named as the object, or functions) of the object that call
    any of them
    """
    components = set(functions)
    block_lists = [(object_name, cfg_object.blocks)] + \
                  [(name, function.blocks) for name, function in cfg_object.functions.items()]
    for component_name, block_list in block_lists:
        if any(block.split_instruction is not None and block.split_instruction.get_op_name() in functions
               for block in block_list.blocks.values()):
            components.add(component_name)
    return components


def _block_list_of(cfg_object, object_name: str, component_name: str):
    return cfg_object.blocks if component_name == object_name else cfg_object.functions[component_name].blocks


def _greedy_components(cfg: CFG, components: Dict[str, set]) -> None:
    """
    Generates the greedy code of the given components
    """
    for object_name, object_components in components.items():
        for component_name in object_components:
            cfg_block_list_spec_ids(_block_list_of(cfg.objectCFG[object_name], object_name, component_name), False)


def _called_candidates(block_list, candidates: set) -> set:
    return {block.split_instruction.get_op_name() for block in block_list.blocks.values()
            if block.split_instruction is not None and block.split_instruction.get_op_name() in candidates}


def _timed_layouts(phase_times: Dict[str, float], *layout_args, **layout_kwargs) -> None:
    """
    layout_generation_cfg, adding its time to phase_times: the liveness analysis (and the calling conventions) it
    performs to "liveness", and the rest to "layouts", as layout_generation does for the other conventions
    """
    start = dtimer()
    init_time_liveness, end_time_liveness = layout_generation_cfg(*layout_args, **layout_kwargs)
    liveness_time = end_time_liveness - init_time_liveness
    phase_times["liveness"] += liveness_time
    phase_times["layouts"] += dtimer() - start - liveness_time


def generate_with_best_conventions(cfg: CFG, layout_dir: Path, args: argparse.Namespace,
                                   selected: Dict[str, set], phase_times: Dict[str, float]) -> None:
    """
    --call-convention best: generates the layouts and the greedy code of the CFG (recursively), where each function
    keeps the "orders" convention only if its cost (see _candidate_costs) is lower than with the Yul order:
    - candidates: the functions whose "orders" convention differs from the Yul order; the components they affect are
      the candidates and the components that call them (the rest of the code does not depend on the convention);
    - the affected components are generated with "orders" (the only extra generation) and their state is saved; then
      the conventions are undone;
    - the whole CFG is generated as usual (Yul order), which also gives the cost of the candidates with the Yul order;
    - the selected functions get the "orders" convention. The components affected by them whose relevant candidates
      (itself and the candidates it calls) are all selected recover the saved state, as it is the same; only the
      rest are generated again
    """
    # The liveness is computed once and reused by every generation below (it does not depend on the conventions)
    start = dtimer()
    results = perform_liveness_analysis_from_cfg_info(construct_analysis_info(cfg))
    phase_times["liveness"] += dtimer() - start
    candidates, components = dict(), dict()
    for object_name, object_liveness in results.items():
        cfg_object = cfg.objectCFG[object_name]
        object_candidates = candidate_functions(cfg_object, object_liveness, "orders")
        if object_candidates:
            candidates[object_name] = object_candidates
            components[object_name] = _components_calling(cfg_object, object_name, object_candidates)

    orders_costs, saved = dict(), dict()
    if candidates:
        args_orders = copy.copy(args)
        args_orders.visualize = False
        args_orders.call_convention = "best"
        args_orders.call_convention_selected = candidates
        args_orders.record_conventions = dict()
        _timed_layouts(phase_times, cfg, args_orders, layout_dir, components, results=results)
        start = dtimer()
        _greedy_components(cfg, components)
        phase_times["greedy"] += dtimer() - start
        orders_costs = _candidate_costs(cfg, candidates, components)
        for object_name, object_components in components.items():
            cfg_object = cfg.objectCFG[object_name]
            for component_name in object_components:
                block_list = _block_list_of(cfg_object, object_name, component_name)
                saved[(object_name, component_name)] = (
                    {block_id: dict(block.__dict__) for block_id, block in block_list.blocks.items()},
                    block_list.needs_repair, block_list.to_fix)
                for block in block_list.blocks.values():
                    block._spec = None
        for object_name, conventions in args_orders.record_conventions.items():
            undo_calling_conventions(cfg.objectCFG[object_name], conventions)

    # Usual generation, with the Yul order
    args_fixed = copy.copy(args)
    args_fixed.call_convention = "fixed"
    _timed_layouts(phase_times, cfg, args_fixed, layout_dir, results=results)
    start = dtimer()
    for cfg_object in cfg.get_objects().values():
        cfg_object_spec_ids(cfg_object, False)
    phase_times["greedy"] += dtimer() - start

    if candidates:
        fixed_costs = _candidate_costs(cfg, candidates, components)
        level_selected = dict()
        for (object_name, function_name), fixed_cost in fixed_costs.items():
            if orders_costs[(object_name, function_name)] < fixed_cost:
                level_selected.setdefault(object_name, set()).add(function_name)
        num_candidates = sum(len(functions) for functions in candidates.values())
        print(f"Call convention best: orders in {sum(len(f) for f in level_selected.values())} of {num_candidates} "
              f"candidate functions")
        if level_selected:
            selected.update(level_selected)
            regenerate, reuse = dict(), []
            for object_name, functions in level_selected.items():
                cfg_object = cfg.objectCFG[object_name]
                for component_name in _components_calling(cfg_object, object_name, functions):
                    block_list = _block_list_of(cfg_object, object_name, component_name)
                    relevant = _called_candidates(block_list, candidates[object_name])
                    if component_name in candidates[object_name]:
                        relevant.add(component_name)
                    if relevant <= functions:
                        reuse.append((object_name, component_name))
                    else:
                        regenerate.setdefault(object_name, set()).add(component_name)
            for object_name, object_components in regenerate.items():
                cfg_object = cfg.objectCFG[object_name]
                for component_name in object_components:
                    for block in _block_list_of(cfg_object, object_name, component_name).blocks.values():
                        block._spec = None
            # The conventions are applied to the selected functions (and only the mixed components are generated)
            args_best = copy.copy(args)
            args_best.call_convention = "best"
            args_best.call_convention_selected = level_selected
            _timed_layouts(phase_times, cfg, args_best, layout_dir, regenerate, results=results)
            start = dtimer()
            _greedy_components(cfg, regenerate)
            phase_times["greedy"] += dtimer() - start
            for object_name, component_name in reuse:
                block_states, needs_repair, to_fix = saved[(object_name, component_name)]
                block_list = _block_list_of(cfg.objectCFG[object_name], object_name, component_name)
                for block_id, state in block_states.items():
                    block_list.blocks[block_id].__dict__.update(state)
                block_list.needs_repair, block_list.to_fix = needs_repair, to_fix

    for cfg_object in cfg.get_objects().values():
        sub_object = cfg_object.get_subobject()
        if sub_object is not None:
            generate_with_best_conventions(sub_object, layout_dir, args, selected, phase_times)


def _needs_repair(cfg: CFG) -> bool:
    for cfg_object in cfg.get_objects().values():
        block_lists = [cfg_object.blocks] + [function.blocks for function in cfg_object.functions.values()]
        if any(getattr(block_list, "needs_repair", False) for block_list in block_lists):
            return True
        if cfg_object.get_subobject() is not None and _needs_repair(cfg_object.get_subobject()):
            return True
    return False


def analyze_single_cfg(cfg: CFG, final_dir: Path, args: argparse.Namespace, times: List):
    if args.visualize:
        dot_file_dir = final_dir.joinpath("liveness")
        dot_file_dir.mkdir(exist_ok=True, parents=True)
    else:
        dot_file_dir = None

    x_preprocess = dtimer()
    tags_dict = preprocess_cfg(cfg, dot_file_dir, args)
    y_preprocess = dtimer()

    x = dtimer()
    best_conventions = getattr(args, "call_convention", "fixed") == "best"
    best_phase_times = collections.Counter()
    if best_conventions:
        # Layouts and greedy together (see generate_with_best_conventions): their times are split as in the other
        # conventions (liveness to the preprocessing, then layouts, and the greedy below)
        layout_dir = final_dir.joinpath("stack_layouts")
        layout_dir.mkdir(parents=True, exist_ok=True)
        args.call_convention_selected = dict()
        generate_with_best_conventions(cfg, layout_dir, args, args.call_convention_selected, best_phase_times)
        init_time_liveness, end_time_liveness = 0, best_phase_times["liveness"]
    else:
        init_time_liveness, end_time_liveness = layout_generation(cfg, args, final_dir.joinpath("stack_layouts"))
    y = dtimer()

    preprocess_time = (y_preprocess-x_preprocess)+(end_time_liveness-init_time_liveness)
    print("Preprocessing CFG: " + str(preprocess_time) + "s")
    times[2] += (preprocess_time)

    layout_time = (y-x)-(end_time_liveness-init_time_liveness)-best_phase_times["greedy"]
    print("Layout generation: " + str(layout_time) + "s")
    times[3] += (layout_time)

    x = dtimer()
    if best_conventions:
        needs_repair = _needs_repair(cfg)
    else:
        needs_repair, _ = cfg_spec_ids(cfg, final_dir.joinpath("statistics.csv"), args.visualize)
    y = dtimer()

    greedy_time = (y - x) + best_phase_times["greedy"]
    print("Greedy algorithm: " + str(greedy_time) + "s")
    times[4] += greedy_time

    if args.sfs:
        sfs_from_cfg(cfg, final_dir)

    repair_time = 0
    # Only count time if repair is needed
    info_colouring = []
    if needs_repair:
        x = dtimer()
        info_colouring = repair_cfg(cfg, final_dir.joinpath("repair") if args.visualize else None)
        y = dtimer()
        repair_time = (y - x)
        times[4] += repair_time

    print("Repair algorithm: " + str(repair_time) + "s")

    if constants.PUSH_DUP:
        # Once the final code of every block is known (after the reparation), PUSHes of values already in the stack
        # become DUPs
        x = dtimer()
        cfg_push_to_dup(cfg)
        times[4] += dtimer() - x

    if args.visualize:
        asm_code = final_dir.joinpath("asm")
        asm_code.mkdir(exist_ok=True, parents=True)
    else:
        asm_code = None

    x = dtimer()
    json_asm_contract = asm_from_cfg(cfg, tags_dict, args.source, asm_code, args.auxdata)
    y = dtimer()

    print("ASM generation: " + str(y - x) + "s")
    times[5] += (y - x)

    return json_asm_contract, info_colouring


# The Yul code refers to AST ids (e.g. object names such as Token_809, function names or the ids of the immutables),
# which differ between the copies of the same contract defined in several source files
AST_ID_SUFFIX_REGEX = re.compile(r"(?<=[A-Za-z0-9_$])_(\d+)(?!\d)")


def canonical_yul_cfg(yul_cfg: Yul_CFG_T) -> str:
    """
    Representation of a Yul CFG in which the AST ids are renamed consistently (in order of appearance), so that two
    copies of the same contract that only differ in the ids have the same representation
    """
    renaming = dict()

    def rename_ids(text: str) -> str:
        return AST_ID_SUFFIX_REGEX.sub(lambda match: f"_#{renaming.setdefault(match.group(1), len(renaming))}", text)

    def walk(node, immutable_ids: bool = False):
        if isinstance(node, dict):
            op = node.get("op")
            return {rename_ids(key): walk(value, key == "literalArgs" and op in ("setimmutable", "loadimmutable"))
                    for key, value in node.items()}
        elif isinstance(node, list):
            return [walk(value, immutable_ids) for value in node]
        elif isinstance(node, str):
            if immutable_ids and node.isdigit():
                return f"#{renaming.setdefault(node, len(renaming))}"
            return rename_ids(node)
        return node

    return json.dumps(walk(yul_cfg))


def find_contract_copies(json_dict: Dict[str, Yul_CFG_T]) -> Dict[str, str]:
    """
    Detects the contracts whose Yul CFGs only differ in the AST ids. Returns the representative (the first
    appearance) of each copy
    """
    representative = dict()
    copy_of = dict()
    for contract_name, yul_cfg in json_dict.items():
        canonical = canonical_yul_cfg(yul_cfg)
        if canonical in representative:
            copy_of[contract_name] = representative[canonical]
        else:
            representative[canonical] = contract_name
    return copy_of


def main(args):
    print("Grey Main")
    
    times = [0, 0, 0, 0, 0, 0, 0]

    x = dtimer()
    json_dict, settings = yul_cfg_dict_from_format(args.input_format, args.source,
                                                   args.contract, args.solc_executable)
    y = dtimer()
    times[0] += (y - x)

    print("Yul CFG Generation", y - x)

    # Copies of the same contract (e.g. flattened sources) are optimized once and their result is reused. The
    # contracts are still reported in their original order
    contract_order = list(json_dict.keys())
    copy_of = find_contract_copies(json_dict)
    for copy_name, contract_name in copy_of.items():
        print(f"Contract copy: {copy_name} -> {contract_name}")

    # Whether solc's block deduplicator runs on the generated assembly (used by the merging of equivalent blocks)
    args.solc_deduplicates = args.solc_dedup == "on" or \
        (args.solc_dedup == "auto" and importer_deduplicates_blocks(args.solc_executable))
    print("solc deduplicates the blocks of the assembly:", args.solc_deduplicates)

    final_dir = Path(args.folder)
    constants.DEBUG_DIR = final_dir.joinpath("debug")

    if constants.DEBUG:
        with open(debug_file('intermediate.json'), 'w') as f:
            json.dump(json_dict, f, indent=4)

    # The copies are not parsed nor optimized (the result of their representative is reused)
    json_dict = {contract_name: yul_cfg for contract_name, yul_cfg in json_dict.items()
                 if contract_name not in copy_of}

    x = dtimer()
    cfgs = parse_CFG_from_json_dict(json_dict, args.builtin)
    y = dtimer()

    print("CFG Parser: " + str(y - x) + "s")
    times[1] += (y - x)

    final_dir.mkdir(exist_ok=True, parents=True)
    asm_contracts = defaultdict(lambda: dict())
    asm_contracts_after_importer = defaultdict(lambda: dict())

    total_blocks_cfg = 0
    total_ins_cfg = 0

    contract_info = []
    call_freq = []
    info_repair = []
    # Results of each optimized contract, reused for its copies
    results = dict()
    for cfg_name in contract_order:
        if cfg_name in copy_of:
            asm_contract, importer_result = results[copy_of[cfg_name]]
            asm_contracts[cfg_name]["asm"] = asm_contract
            if not args.json_solc:
                print("Contract: " + cfg_name + " -> EVM Code: " + importer_result)
                contract_info.append({"contract": cfg_name, "bin_code": importer_result,
                                      "num_bytes": len(importer_result) // 2})
            else:
                contract_info.append({"contract": cfg_name, "bin_code": importer_result})
                asm_contracts_after_importer[cfg_name]["asm"] = asm_from_opcodes(importer_result)
            continue

        cfg = cfgs[cfg_name]
        blocks, ins = cfg.get_stats()
        
        total_blocks_cfg+=blocks
        total_ins_cfg += ins
        
        #      print("Synthesizing...", cfg_name)
        cfg_dir = final_dir.joinpath(cfg_name)
        asm_contract, info_repair_cfg = analyze_single_cfg(cfg, cfg_dir, args, times)
        for row in info_repair_cfg:
            row["contract"] = cfg_name
        info_repair.extend(info_repair_cfg)
        asm_contracts[cfg_name]["asm"] = asm_contract

        # Store the call info in a csv
        call_freq.extend(function_frequency(cfg, cfg_name))

        if args.visualize:
            assembly_path = store_asm_output(asm_contract, cfg_name, cfg_dir)

        if args.inline:
            # solc's inliner is only allowed to copy the functions in which inlining reduces the number of
            # instructions. With --no-inline the importer keeps its standard behaviour
            restrict_importer_inlining(asm_contract)

        std_assembly_path = store_asm_standard_json_output(asm_contract, cfg_name, cfg_dir, settings)
        # print(std_assembly_path)
        # synt_binary = SolidityCompilation.importer_assembly_file(assembly_path, solc_executable=args.solc_executable)

        x = dtimer()
        if not args.json_solc:
            synt_binary_stdjson = SolidityCompilation.importer_assembly_standard_json_file(std_assembly_path,
                                                                                           deployed_contract=cfg_name,
                                                                                           solc_executable=args.solc_executable)


            print("Contract: " + cfg_name + " -> EVM Code: " + synt_binary_stdjson)
            contract_info.append({"contract": cfg_name, "bin_code": synt_binary_stdjson,
                                   "num_bytes": len(synt_binary_stdjson) // 2})
            results[cfg_name] = (asm_contract, synt_binary_stdjson)

            if args.visualize:
                store_binary_output(cfg_name, synt_binary_stdjson, cfg_dir)

        else:
            synt_opcodes_stdjson = SolidityCompilation.importer_assembly_standard_json_file(std_assembly_path,
                                                                                            deployed_contract=cfg_name,
                                                                                            solc_executable=args.solc_executable,
                                                                                            selected_result="opcodes")
            contract_info.append({"contract": cfg_name, "bin_code": synt_opcodes_stdjson})

            asm_contracts_after_importer[cfg_name]["asm"] = asm_from_opcodes(synt_opcodes_stdjson)
            results[cfg_name] = (asm_contract, synt_opcodes_stdjson)

        y = dtimer()

        print("solc importer: " + str(y - x) + "s")
        times[6] += (y - x)

    times_str = map(lambda x: str(x), times)
    print("Times " + args.source + ": " + ",".join(times_str))
    print("Total times " + args.source +": "+ str(sum(times)))

    print("Total Blocks CFG "+ args.source +": "+str(total_blocks_cfg))
    print("Total Ins CFG "+ args.source +": "+str(total_ins_cfg))
    
    asm_combined_output = {"contracts": asm_contracts, "version": "grey"}

    pd.DataFrame(call_freq).to_csv(final_dir.joinpath(f"call_info_{Path(args.source).stem}.csv"))
    pd.DataFrame(info_repair).to_csv(final_dir.joinpath(f"repair_{Path(args.source).stem}.csv"))

    with open(str(final_dir.joinpath(Path(args.source).stem)) + "_bef_importer.json_solc", 'w') as f:
        json.dump(asm_combined_output, f, indent=4)

    # We store the combined output as well after the importer
    if args.json_solc:
        with open(str(final_dir.joinpath(Path(args.source).stem)) + "_aft_importer.json_solc", 'w') as f:
            json.dump({"contracts": asm_contracts_after_importer, "version": "grey"}, f, indent=4)

    pd.DataFrame(contract_info).to_csv(final_dir.joinpath(f"{Path(args.source).stem}.csv"))
