"""
Script for checking with hevm that the runtime bytecode generated by grey is equivalent to a reference.
It works over the output folder produced by compare_repair_slots.py with --keep-outputs
(<output_dir>/runs/before/<run>, <output_dir>/runs/after/<run> and <output_dir>/comparison.csv), and
only considers the contracts whose assembly differs between both versions.

Two references are available:
  - "before" (default): the runtime code generated by the other version of grey. Useful to check a
    change, but it cannot detect bugs shared by both versions.
  - "solc": the runtime code generated by solc from the original standard-json input (only for
    inputs in standard-json format), i.e. an independent reference.

For each contract, the stored "<contract>_standard_json_output.json" (the assembly fed to the solc
importer) is compiled again requesting the deployed bytecode, and both runtime codes are compared
with "hevm equivalence".

Usage:
  python3 check_equivalence_hevm.py <output_dir> [--reference before|solc] [--solc <solc>] [--hevm <hevm>]
      [--timeout S] [--jobs N]
"""

import argparse
import json
import re
import subprocess
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import pandas as pd

ASM_SUFFIX = "_standard_json_output.json"
REPO_ROOT = Path(__file__).resolve().parent.parent

# Unlinked library references appear as __$<34 hex chars>$__ placeholders, which hevm cannot parse.
# We link them to the same dummy address in both codes (external calls are symbolic in hevm anyway)
LIBRARY_PLACEHOLDER = re.compile(r"__\$[0-9a-fA-F]{34}\$__")
DUMMY_LIBRARY_ADDRESS = "0" * 39 + "1"


def link_placeholders(code: str) -> str:
    return LIBRARY_PLACEHOLDER.sub(DUMMY_LIBRARY_ADDRESS, code)


def runtime_code_from_assembly(assembly_file: Path, solc_executable: Path) -> str:
    """
    Invokes the solc assembly importer on the stored standard-json and returns the deployed bytecode
    of the (only) contract in it
    """
    standard_json = json.loads(assembly_file.read_text())
    standard_json["settings"]["outputSelection"] = {"*": {"": ["evm.deployedBytecode.object"]}}
    completed = subprocess.run([str(solc_executable), "--standard-json"], input=json.dumps(standard_json),
                               capture_output=True, text=True, check=True)
    contracts = json.loads(completed.stdout)["contracts"]
    assert len(contracts) == 1, f"Expected a single contract in {assembly_file}"
    contract_info = next(iter(contracts.values()))[""]
    return link_placeholders(contract_info["evm"]["deployedBytecode"]["object"])


def _compile_standard_json(standard_json: Dict, source: Path, solc_executable: Path) -> Dict:
    completed = subprocess.run([str(solc_executable), "--standard-json"], input=json.dumps(standard_json),
                               capture_output=True, text=True, cwd=source.parent)
    return json.loads(completed.stdout)


def runtime_codes_from_solc(source: Path, solc_executable: Path) -> Dict[str, Optional[str]]:
    """
    Compiles the original standard-json input with solc and returns the deployed bytecode of each
    contract name (None if the name is ambiguous, i.e. it appears in several files)
    """
    standard_json = json.loads(source.read_text())
    standard_json.setdefault("settings", {})["outputSelection"] = {"*": {"*": ["evm.deployedBytecode.object"]}}
    output = _compile_standard_json(standard_json, source, solc_executable)
    if not output.get("contracts"):
        # Stack-too-deep contracts can only be compiled through the IR pipeline (the one used by grey)
        standard_json["settings"]["viaIR"] = True
        output = _compile_standard_json(standard_json, source, solc_executable)
    codes: Dict[str, Optional[str]] = {}
    for file_contracts in output.get("contracts", {}).values():
        for contract_name, contract_info in file_contracts.items():
            code = contract_info.get("evm", {}).get("deployedBytecode", {}).get("object", "")
            if not code:
                continue
            codes[contract_name] = None if contract_name in codes else link_placeholders(code)
    return codes


def check_codes(code_a: str, code_b: str, hevm_executable: str, timeout: int) -> Tuple[str, Optional[str]]:
    """
    Returns the verdict (identical, equivalent, not_equivalent, timeout, error) and extra information
    """
    if code_a == code_b:
        return "identical", None
    try:
        completed = subprocess.run([hevm_executable, "equivalence", "--code-a", code_a, "--code-b", code_b],
                                   capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return "timeout", None
    # hevm prints "No discrepancies found" when the codes are proven equivalent and
    # "Not equivalent" together with a counterexample otherwise
    output = completed.stdout + completed.stderr
    last_line = output.strip().splitlines()[-1] if output.strip() else None
    if completed.returncode == 0 and "No discrepancies found" in output:
        return "equivalent", None
    if "Not equivalent" in output:
        return "not_equivalent", last_line
    return "error", last_line


def changed_contracts(output_dir: Path) -> List[Tuple[str, Path, Path]]:
    """
    Returns the (run name, assembly before, assembly after) of the contracts whose assembly differs. The runs
    of the "before" version with several seeds are compared with the first seed available
    """
    pairs = []
    before_runs = {}
    for run_folder in sorted(output_dir.joinpath("runs", "before").iterdir()):
        before_runs.setdefault(run_folder.name.rsplit("_s", 1)[0], run_folder)
    for after_run in sorted(output_dir.joinpath("runs", "after").iterdir()):
        before_run = before_runs.get(after_run.name.rsplit("_s", 1)[0])
        if before_run is None:
            continue
        for assembly_after in sorted(after_run.rglob(f"*{ASM_SUFFIX}")):
            assembly_before = before_run.joinpath(assembly_after.relative_to(after_run))
            if not assembly_before.exists() or assembly_before.read_bytes() != assembly_after.read_bytes():
                pairs.append((after_run.name, assembly_before, assembly_after))
    return pairs


def main():
    parser = argparse.ArgumentParser(description="Check equivalence of grey outputs with hevm")
    parser.add_argument("output_dir", type=Path)
    parser.add_argument("--reference", choices=["before", "solc"], default="before")
    parser.add_argument("--solc", type=Path, default=REPO_ROOT.joinpath("examples/solc-without-opt"))
    parser.add_argument("--hevm", type=str, default="hevm")
    parser.add_argument("--timeout", type=int, default=900)
    parser.add_argument("--jobs", type=int, default=4)
    parser.add_argument("--only-skipped", action="store_true", dest="only_skipped",
                        help="Only check again the contracts skipped in a previous execution")
    args = parser.parse_args()

    output_dir = args.output_dir.resolve()
    solc_executable = args.solc.resolve()
    pairs = changed_contracts(output_dir)
    if args.only_skipped:
        previous = pd.read_csv(output_dir.joinpath(f"equivalence_{args.reference}.csv"))
        skipped = set(zip(previous[previous["verdict"] == "skipped"]["run"],
                          previous[previous["verdict"] == "skipped"]["contract"]))
        pairs = [pair for pair in pairs if (pair[0], pair[2].parent.name) in skipped]
    print(f"Contracts whose assembly differs: {len(pairs)}")

    # For the solc reference, compile each original input only once
    sources, solc_codes = {}, {}
    if args.reference == "solc":
        comparison = pd.read_csv(output_dir.joinpath("comparison.csv"))
        for _, row in comparison.iterrows():
            sources[f"{row['input']}_d{row['depth']}"] = (Path(row["source"]), row["input_format"])
        for run_name in dict.fromkeys(run_name for run_name, _, _ in pairs):
            source, input_format = sources[run_name.rsplit("_s", 1)[0]]
            if input_format == "standard-json" and source not in solc_codes:
                solc_codes[source] = runtime_codes_from_solc(source, solc_executable)

    def check(pair: Tuple[str, Path, Path]) -> Tuple[str, str, str, Optional[str]]:
        run_name, assembly_before, assembly_after = pair
        contract_name = assembly_after.parent.name
        try:
            code_after = runtime_code_from_assembly(assembly_after, solc_executable)
            if args.reference == "before":
                code_reference = runtime_code_from_assembly(assembly_before, solc_executable)
            else:
                source, input_format = sources[run_name.rsplit("_s", 1)[0]]
                if input_format != "standard-json":
                    return run_name, contract_name, "skipped", f"input format {input_format}"
                code_reference = solc_codes[source].get(contract_name)
                if code_reference is None:
                    return run_name, contract_name, "skipped", "contract not found (or ambiguous) in solc output"
        except Exception as exception:
            return run_name, contract_name, "error", f"solc: {exception}"
        verdict, info = check_codes(code_reference, code_after, args.hevm, args.timeout)
        return run_name, contract_name, verdict, info

    with ThreadPoolExecutor(max_workers=args.jobs) as executor:
        results = list(executor.map(check, pairs))

    results_file = output_dir.joinpath(f"equivalence_{args.reference}{'_skipped' if args.only_skipped else ''}.csv")
    pd.DataFrame(results, columns=["run", "contract", "verdict", "info"]).to_csv(results_file, index=False)

    for verdict in ["identical", "equivalent", "not_equivalent", "timeout", "error", "skipped"]:
        matching = [result for result in results if result[2] == verdict]
        print(f"{verdict}: {len(matching)}")
        if verdict in ["not_equivalent", "error"]:
            for run_name, contract_name, _, info in matching:
                print(f"  {run_name}/{contract_name}: {info}")


if __name__ == "__main__":
    main()
