"""
Script for comparing the bytecode generated by grey with the one generated by solc (via-IR pipeline) for the
same inputs. It works over the output folder produced by compare_repair_slots.py with --keep-outputs, using
the runs of the "after" version (or "before", with --version before) at a given depth
(<output_dir>/runs/<version>/<run>_d<depth>_s*).

For each input, the original source is compiled again with the same solc binary used by grey (read from
the run log) and the same settings grey uses:
  - standard-json inputs: their own settings with viaIR and the optimizer enabled and no metadata (as grey does
    when generating the Yul CFG and importing the assembly);
  - sol inputs: the optimizer enabled with the default settings (grey uses --optimize).
Then, the creation bytecode of each contract is compared with the one generated by grey (stored in
<run>/<stem>.csv), both in size and in the bytes per category of opcode:
  - stack: DUPx, SWAPx, POP
  - jump: JUMP, JUMPI, JUMPDEST and the PUSHes of jump targets (PUSHx followed by JUMP/JUMPI)
  - push: the remaining PUSHes (constants)
  - memory: MLOAD, MSTORE, MSTORE8 (includes the spills of the reparation phase)
  - other: the remaining opcodes
The categories are computed by a linear scan, so data sections might be misclassified (in both codes).

The results are stored in <output_dir>/solc_comparison.csv (solc_comparison_before.csv for --version before; one
row per contract) and a summary is printed.

Usage:
  python3 compare_with_solc.py <output_dir> [--depth 16] [--jobs N] [--version after|before]
"""

import argparse
import csv
import json
import shlex
import subprocess
from collections import Counter
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import pandas as pd

from check_equivalence_hevm import link_placeholders

CATEGORIES = ["stack", "jump", "push", "memory", "other"]
METADATA_SETTINGS = {"appendCBOR": False, "useLiteralContent": False, "bytecodeHash": "none"}


def bytes_per_category(code: str) -> Counter:
    """
    Number of bytes of the code for each category of opcode (see the module docstring)
    """
    code_bytes = bytes.fromhex(link_placeholders(code))
    instructions = []
    i = 0
    while i < len(code_bytes):
        opcode = code_bytes[i]
        size = 1 + (opcode - 0x5f if 0x60 <= opcode <= 0x7f else 0)
        instructions.append((opcode, size))
        i += size

    counter = Counter()
    for position, (opcode, size) in enumerate(instructions):
        next_opcode = instructions[position + 1][0] if position + 1 < len(instructions) else None
        if 0x80 <= opcode <= 0x9f or opcode == 0x50:
            category = "stack"
        elif opcode in (0x56, 0x57, 0x5b) or (0x60 <= opcode <= 0x7f and next_opcode in (0x56, 0x57)):
            category = "jump"
        elif 0x5f <= opcode <= 0x7f:
            category = "push"
        elif opcode in (0x51, 0x52, 0x53):
            category = "memory"
        else:
            category = "other"
        counter[category] += size
    return counter


def solc_from_log(log_file: Path) -> Optional[str]:
    """
    Solc binary passed to grey in the run (first line of the log contains the command)
    """
    command = shlex.split(log_file.read_text().splitlines()[0])
    return command[command.index("-solc") + 1] if "-solc" in command else None


def solc_bytecodes(source: Path, input_format: str, solc_executable: str) -> Tuple[Dict[str, Optional[str]], str]:
    """
    Compiles the source with solc (via-IR) and returns the creation bytecode per contract name (None if the name
    is ambiguous) and an error message (empty if the compilation succeeded)
    """
    if input_format == "standard-json":
        standard_json = json.loads(source.read_text())
    else:
        standard_json = {"language": "Solidity", "sources": {source.name: {"content": source.read_text()}},
                         "settings": {"optimizer": {"enabled": True}}}
    settings = standard_json.setdefault("settings", {})
    settings["viaIR"] = True
    # grey always optimizes (the Yul CFG and the importer), so solc is compiled with the optimizer enabled as well
    settings.setdefault("optimizer", {})["enabled"] = True
    settings["metadata"] = dict(METADATA_SETTINGS)
    settings["outputSelection"] = {"*": {"*": ["evm.bytecode.object"]}}
    completed = subprocess.run([solc_executable, "--standard-json"], input=json.dumps(standard_json),
                               capture_output=True, text=True, cwd=source.parent)
    output = json.loads(completed.stdout)
    errors = [error["formattedMessage"].splitlines()[0] for error in output.get("errors", [])
              if error.get("severity") == "error"]

    codes: Dict[str, Optional[str]] = {}
    for file_contracts in output.get("contracts", {}).values():
        for contract_name, contract_info in file_contracts.items():
            code = contract_info.get("evm", {}).get("bytecode", {}).get("object", "")
            if code:
                codes[contract_name] = None if contract_name in codes else code
    return codes, "; ".join(errors)


def grey_bytecodes(run_folder: Path) -> Dict[str, str]:
    """
    Creation bytecode per contract name generated by grey in the run
    """
    codes = {}
    for csv_file in run_folder.glob("*.csv"):
        if csv_file.name.startswith(("call_info_", "repair_", "statistics")):
            continue
        with open(csv_file) as f:
            for row in csv.DictReader(f):
                if row.get("bin_code"):
                    codes[row["contract"].split(":")[-1]] = row["bin_code"]
    return codes


def compare_run(run_folder: Path, log_file: Path, source: Path, input_format: str) -> List[Dict]:
    solc_executable = solc_from_log(log_file)
    grey_codes = grey_bytecodes(run_folder)
    solc_codes, error = solc_bytecodes(source, input_format, solc_executable)
    rows = []
    for contract, grey_code in sorted(grey_codes.items()):
        solc_code = solc_codes.get(contract)
        row = {"run": run_folder.name, "contract": contract, "grey_bytes": len(grey_code) // 2,
               "solc_bytes": len(solc_code) // 2 if solc_code else None,
               "solc_error": error if solc_code is None else ""}
        if solc_code:
            grey_categories, solc_categories = bytes_per_category(grey_code), bytes_per_category(solc_code)
            for category in CATEGORIES:
                row[f"grey_{category}"] = grey_categories[category]
                row[f"solc_{category}"] = solc_categories[category]
        rows.append(row)
    return rows


def main():
    parser = argparse.ArgumentParser(description="Compare the bytecode of grey and solc (via-IR)")
    parser.add_argument("output_dir", type=Path)
    parser.add_argument("--depth", type=int, default=16)
    parser.add_argument("--jobs", type=int, default=8)
    parser.add_argument("--version", choices=["after", "before"], default="after",
                        help="Version of the compare_repair_slots.py run that is compared with solc")
    args = parser.parse_args()

    comparison = pd.read_csv(args.output_dir.joinpath("comparison.csv"))
    comparison = comparison[(comparison["depth"] == args.depth) & comparison["error_after"].isna()]

    tasks = []
    for _, input_row in comparison.iterrows():
        run_folders = sorted(args.output_dir.joinpath("runs", args.version).glob(f"{input_row['input']}_d{args.depth}_s*"))
        if not run_folders:
            continue
        log_file = args.output_dir.joinpath("logs", args.version, run_folders[0].name + ".txt")
        tasks.append((run_folders[0], log_file, Path(input_row["source"]), input_row["input_format"]))

    rows = []
    with ProcessPoolExecutor(max_workers=args.jobs) as executor:
        for run_rows in executor.map(compare_run, *zip(*tasks)):
            rows.extend(run_rows)

    results = pd.DataFrame(rows)
    results["diff"] = results["grey_bytes"] - results["solc_bytes"]
    for category in CATEGORIES:
        results[f"diff_{category}"] = results[f"grey_{category}"] - results[f"solc_{category}"]
    csv_name = "solc_comparison.csv" if args.version == "after" else f"solc_comparison_{args.version}.csv"
    results.to_csv(args.output_dir.joinpath(csv_name), index=False)

    compared = results[results["solc_bytes"].notna()]
    print(f"Contracts compared: {len(compared)} (solc failed or ambiguous: {len(results) - len(compared)})")
    print(f"grey smaller: {(compared['diff'] < 0).sum()}, larger: {(compared['diff'] > 0).sum()}, "
          f"equal: {(compared['diff'] == 0).sum()}")
    print(f"Total bytes: grey {int(compared['grey_bytes'].sum())}, solc {int(compared['solc_bytes'].sum())}")
    worse = compared[compared["diff"] > 0]
    print("Bytes per category in the contracts where grey is larger (grey - solc): " +
          ", ".join(f"{category} {int(worse[f'diff_{category}'].sum())}" for category in CATEGORIES))


if __name__ == "__main__":
    main()
